let BLK = "0B"
let CHR = "0B"
let DIR = "04"
let EXE = "06"
let REG = "00"
let HARDLINK = "06"
let SYMLINK = "06"
let MISSING = "00"
let ORPHAN = "09"
let FIFO = "06"
let SOCK = "0B"
let OTHER = "06"

$env.NNN_FCOLORS = $"($BLK)($CHR)($DIR)($EXE)($REG)($HARDLINK)($SYMLINK)($MISSING)($ORPHAN)($FIFO)($SOCK)($OTHER)"
